### ISSUE TITLE
Could you provide an example shellcode.bin?

### ISSUE THREAD

**Issue by garlicuncle** [connormcgarr/LittleCorporal#3]
Hello!

Thanks for your awesome project.
I tried to use the files, but it doesn't seem to execute the payload I created.
I simply tried to launch calc.exe, but it does not work.
The .bin was created with:
msfvenom -p windows/exec CMD=calc.exe -b '\x00\x0A\0x0D' -f c --platform windows --arch x64 -o a.bin

is this correct?
Could you otherwise provide an example .bin or a command to create one?

**Comment by connormcgarr** [comment]
Hi there! To address your concern, I would first note that the issue you've opened is **not** an issue with the LittleCorporal project. Generating a `.bin` is not a documented step within LittleCorporal, nor is it mentioned anywhere as such. This is because the generation of a `.bin` shellcode blob is highly dependent on the mechanism, tool, or framework leveraged to generate the `.bin`. However, I would recommend looking into "how to generate a .bin payload with msfvenom", based on your comment. 

If you find yourself with any other issues with the tool itself - please don't hesitate to open a new issue.
