### ISSUE TITLE
Word 2019

### ISSUE THREAD

**Issue by 0xElessar** [connormcgarr/LittleCorporal#4]
Hey @connormcgarr ,

thank you for the tool.

Did you manage to test it in Word 2019? I just created a .doc file, started it but nothing happens. No warning about Macro or anything. If I Run autoopen function manually, nothing happens as well :(

The Macro is definitely in the file. Maybe Word 2019 by default blocks Macros in older file types I am wondering?

.NET 2.0 is definitely installed.

When I install Office 2016, I will definitely re-check it.

thanks

**Comment by 0xElessar** [comment]
I am an idiot again!

Nothing happens ?!? From user UI perspective only!!! Shellcode executes beautifully in background and with proper PPID spoofing.

Great work, @connormcgarr !!!

BTW is there any chance to drop .NET version 2 requirement? This is no longer default Windows OS configuration and this limits what targets we can choose in our assessments.

**Comment by connormcgarr** [comment]
Hi there -- glad to hear it works! As far as the .NET v2, it's something I can look into. And with .NET v2, if you read the documentation, you will see that is actually what is used by .NET v3.5. So yes, it is older, but it's definitely something still used -- especially for backwards compatibility. 

If you want to open up a feature request or a pull request, I could look into it. There is also the added requirement of needing 64-bit Word in order to run. This is also something that may not be the case in some environments. I'm saying all of this because there are definitely some improvements to be made, I just haven't had time to address them because my focus has been elsewhere. If you make a fix to the tool for this I'd be more than happy to incorporate it!
